server:
  port: 8083

spring:
  config:
    activate:
      on-profile: dev

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group-dev
      auto-offset-reset: earliest

  mail:
    host: smtp.gmail.com
    port: 587
    username: dev-email@gmail.com
    password: dev-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: DEBUG