server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://mysql-menu:3306/menu_db
    username: root
    password: Arman@1981

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka